<?php

namespace Remarque\NoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemarqueParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemarqueParticipantRepository extends EntityRepository
{
	public function myFindOne($remarque,$participant)
{
  $qb = $this->createQueryBuilder('a');

  $qb
    ->where('a.remarque = :remarque')
     ->setParameter('remarque',$remarque)
    ->andwhere('a.participant = :participant')
     ->setParameter('participant',$participant)
    
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
}


}
